source "https://rubygems.org"

gem "thor"
gem "colorize", "~> 0.8.1"
gem "uri"
gem "tty-table", "~> 0.12.0"
gem "tty-spinner", "~> 0.9.3"
gem "down"
gem "tty-prompt"
gem "rubyzip"
gem "public_suffix"
